config/routes.rb
Rails.application.routes.draw do
  root 'players#index'
  get '/edit', to: 'players#edit'
  get 'login', to: 'players#login'
  patch '/update', to: 'players#update'
  resources :players
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.all
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    @player.save
    redirect_to player_path(@player.id)
  end

  def show
    @player = Player.find(params[:id])
    # @player = Player.new(params.require(:player).permit(:nickname, :rank))
  end

  def edit
    @player = Player.find_by(params[:id])
  end

  def update
    @player = Player.find_by(params[:id])
    if @player.update(player_params)
      redirect_to @player
    end
  end

  def destroy
    @player = player.find(params[:id])
    @player.destroy

    redirect_to player_path
  end

  private
  def player_params
    params.require(:player).permit(:nickname, :rank, :charisma, :wisdom)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/edit.html.erb
<%= form_for @player, url: update_path(@player.id) do |f| %>
  Nickname:<br>
  <%= f.text_field :nickname %><br>
  Rank:<br>
  <%= f.text_field :rank %><br>
  Charisma:<br>
  <%= f.text_field :charisma %><br>
  Wisdom:<br>
  <%= f.text_field :wisdom %><br><br>
  <%= f.submit "Save changes" %>
<% end %>

app/views/players/index.html.erb
<%= link_to "New player", new_player_path %><br>
<%= link_to "Show one player", login_path %>
<h1>Listing players</h1>


  <% @players.each do |player| %>
    <tr>
      <td><%= player.nickname %></td>
      <td><%= player.rank %></td>
      <td><%= player.charisma %></td>
      <td><%= player.wisdom %></td>
      <td><%= link_to 'Show', player_path(player) %></td>
    </tr>
  <% end %>

app/views/players/new.html.erb
<%= form_for @player, url: {action: "create"} do |f| %>
  Nickname:<br>
  <%= f.text_field :nickname %><br>
  Rank:<br>
  <%= f.text_field :rank %><br>
  Charisma:<br>
  <%= f.text_field :charisma %><br>
  Wisdom:<br>
  <%= f.text_field :wisdom %><br><br>
  <%= f.submit "Create" %>
<% end %>

app/views/players/show.html.erb
<h1><%= @player.nickname %></h1>
<p><%= @player.rank %>
<p><%= @player.charisma %>
<p><%= @player.wisdom %>
<br><%= link_to "Edit", edit_path %>
<br><%= link_to "Delete", player_path(@player.id), method: :Delete %>